version: '2'
services:
  rabbitmq:
    image: rabbitmq
    ports:
     - "4369:4369"
     - "5671:5671"
     - "15001:5672"
     - "25672:25672"
    environment:
     - RABBITMQ_DEFAULT_USER=cisco
     - RABBITMQ_DEFAULT_PASS=C1sco123
    network_mode: bridge
  vendingmachineapi:
    build:
      context: ./vendingMachineAPI
      dockerfile: ./Dockerfile
    command: /usr/local/bin/python2.7 /usr/src/vendingMachineAPI.py
    links:
      - rabbitmq
    environment:
     - RABBITMQ_DEFAULT_USER=cisco
     - RABBITMQ_DEFAULT_PASS=C1sco123
     - RABBITMQ_HOST=64.100.10.232
     - RABBITMQ_PORT=15001
     - RABBITMQ_QUEUE=HackZurich16
     - DELAY=5
     - PORT=5000
    ports:
     - "5000:5000"
    network_mode: bridge


